import React, { useState, useEffect, useRef } from 'react';
import {
  View,
  Text,
  TouchableOpacity,
  Image,
  StyleSheet,
  SafeAreaView,
  ScrollView,
  Modal,
  Alert,
  ActivityIndicator,
  Linking,
  AppState,
} from 'react-native';
import { FontWeight, FontFamily } from '../styles/typography';
import ApiService from '../services/api';
import paymentService from '../services/paymentService';
import PaymentStatusService from '../services/paymentStatusService';

export default function CheckoutDetailScreen({ navigation, route }) {
  // Get data from previous screens
  const { customerData, product, actionType, paymentData } = route.params || {};

  // State for payment processing
  const [loading, setLoading] = useState(false);
  const [orderData, setOrderData] = useState(null);
  const currentOrderId = useRef(null);

  console.log('CheckoutDetailScreen received:', {
    customerData,
    product,
    actionType,
    paymentData,
  });

  // Payment handlers are now in WebView
  // No need for AppState monitoring

  // Use received data or fallback to default
  const buyer = customerData
    ? {
        name: `${customerData.firstName} ${customerData.lastName}`,
        community: customerData.community || 'Komunitas',
        phone: customerData.phone,
      }
    : {
        name: 'Khalidah Nur Djamil',
        community: 'Komunitas RUS (Rumpun Usaha Sehati)',
        phone: '(+62) 823-1117-8820',
      };

  // Use received product data or fallback to default
  const order = product
    ? {
        image: product.gambarUrl
          ? { uri: product.gambarUrl }
          : require('./assets/absensi-staff.png'),
        name: product.nama || product.title,
        price: paymentService.formatCurrency(
          parseInt(product.harga || product.price || 0),
        ),
        category: product.kategori || 'Produk',
      }
    : {
        image: require('./assets/absensi-staff.png'),
        name: 'Aplikasi Absensi',
        price: 'Rp 2.000.000',
        category: 'Produk',
      };

  // Function to get category display text
  const getCategoryDisplay = (category) => {
    if (!category) return 'Produk';
    const lowerCategory = category.toLowerCase();
    if (lowerCategory === 'produk') return 'Produk';
    if (lowerCategory === 'layanan' || lowerCategory === 'service') return 'Layanan';
    return category; // Return original if not recognized
  };

  // Use received payment data or fallback to default
  const payment = paymentData
    ? {
        method: paymentData.label,
        total: paymentService.formatCurrency(
          parseInt(product?.harga || product?.price || 2000000),
        ),
      }
    : {
        method: 'Kartu Kredit/Debit',
        total: 'Rp 2.000.000',
      };

  // Handle payment processing

  // Handle payment process
  const handlePayment = async () => {
    try {
      setLoading(true);

      // Validate required data
      if (!customerData || !product || !paymentData) {
        Alert.alert(
          'Error',
          'Data tidak lengkap. Silakan ulangi proses pemesanan.',
        );
        return;
      }

      // Prepare order data for Midtrans (Order ID will be generated by backend)
      const orderData = {
        grossAmount: parseInt(product.harga || product.price || 0),
        customerDetails: {
          firstName: customerData.firstName,
          lastName: customerData.lastName,
          email: customerData.email || 'customer@example.com',
          phone: customerData.phone,
        },
        itemDetails: [
          {
            id: product.id || 'PRODUCT-1',
            price: parseInt(product.harga || product.price || 0),
            quantity: 1,
            name: product.nama || product.title || 'Product',
            category: product.kategori || product.category || 'Produk', // Add category for Order ID generation
          },
        ],
        paymentType: paymentData.midtransType, // ewallet, credit_card, bank_transfer
        enabledPayments: paymentData.details?.enabled_payments || [
          paymentData.midtransType,
        ],
      };

      console.log('Creating Midtrans transaction with data:', orderData);

      // Create transaction with Midtrans
      const result = await ApiService.createMidtransTransaction(orderData);
      
      console.log('📥 Midtrans API result:', result);
      console.log('🔍 Result structure:', {
        success: result.success,
        data: result.data,
        message: result.message,
        error: result.error
      });

      if (result.success && result.data) {
        console.log('Midtrans transaction created:', result.data);

        // Get the structured Order ID from backend response
        const backendOrderId = result.data.order_id;
        console.log('📦 Using backend Order ID:', backendOrderId);

        // Store the backend Order ID for status checking
        currentOrderId.current = backendOrderId;

        // Get payment URL based on payment type
        let paymentUrl = null;

        if (result.data.snap_token) {
          // For Snap integration (recommended for mobile)
          paymentUrl = `https://app.sandbox.midtrans.com/snap/v2/vtweb/${result.data.snap_token}`;
        } else if (result.data.redirect_url) {
          // For Core API integration
          paymentUrl = result.data.redirect_url;
        }

        if (paymentUrl) {
          // Navigate to WebView instead of external browser
          console.log('Navigating to MidtransWebViewScreen with:', {
            paymentUrl,
            orderData,
            orderId: backendOrderId
          });
          
          navigation.navigate('MidtransWebViewScreen', {
            paymentUrl: paymentUrl,
            orderData: {
              ...orderData,
              orderId: backendOrderId // Use the structured Order ID from backend
            },
            orderId: backendOrderId, // Pass the structured Order ID
            customerData: customerData,
            product: product
          });
        } else {
          throw new Error(
            'Tidak ada URL pembayaran yang diterima dari Midtrans',
          );
        }
      } else {
        throw new Error(result.message || 'Gagal membuat transaksi pembayaran');
      }
    } catch (error) {
      console.error('Payment creation error:', error);
      Alert.alert(
        'Error Pembayaran',
        `Gagal membuat pembayaran: ${error.message}\n\nSilakan coba lagi atau pilih metode pembayaran lain.`,
      );
    } finally {
      setLoading(false);
    }
  };

  // Check payment status using PaymentStatusService
  const checkPaymentStatus = async (orderId) => {
    if (!orderId) {
      Alert.alert('Error', 'Order ID tidak tersedia untuk pengecekan status.');
      return;
    }

    try {
      console.log('🔍 Checking payment status for orderId:', orderId);
      
      // Show loading indicator
      setLoading(true);

      // Use PaymentStatusService to check status
      const result = await PaymentStatusService.checkPaymentStatus(orderId);

      console.log('💳 Payment status result:', result);

      if (result.success) {
        const { transaction_status, payment_type } = result.data;

        if (transaction_status === 'capture' || transaction_status === 'settlement') {
          // Payment successful
          Alert.alert(
            'Pembayaran Berhasil!',
            `Pembayaran dengan ${payment_type} telah berhasil.`,
            [
              {
                text: 'OK',
                onPress: () => {
                  setLoading(false);
                  currentOrderId.current = null;
                  // Navigate to success screen
                  navigation.navigate('PaymentSuccessScreen', {
                    orderData: { orderId, transaction_status, payment_type },
                    customerData,
                    product,
                  });
                },
              },
            ],
          );
        } else if (transaction_status === 'pending') {
          // Payment still pending
          Alert.alert(
            'Pembayaran Pending',
            'Pembayaran masih dalam proses. Silakan tunggu atau cek status nanti.',
            [{ text: 'OK', onPress: () => setLoading(false) }]
          );
        } else if (transaction_status === 'deny' || transaction_status === 'cancel' || transaction_status === 'expire') {
          // Payment failed or cancelled
          Alert.alert(
            'Pembayaran Gagal',
            `Status pembayaran: ${transaction_status}. Silakan coba lagi.`,
            [
              {
                text: 'OK',
                onPress: () => {
                  setLoading(false);
                  currentOrderId.current = null;
                },
              },
            ]
          );
        } else {
          // Unknown status
          Alert.alert(
            'Status Tidak Dikenal',
            `Status pembayaran: ${transaction_status}`,
            [{ text: 'OK', onPress: () => setLoading(false) }]
          );
        }
      } else {
        // Failed to check status
        Alert.alert(
          'Error',
          result.message || 'Gagal mengecek status pembayaran.',
          [{ text: 'OK', onPress: () => setLoading(false) }]
        );
      }
    } catch (error) {
      console.error('❌ Error checking payment status:', error);
      Alert.alert(
        'Error',
        `Gagal mengecek status pembayaran: ${error.message}`,
        [{ text: 'OK', onPress: () => setLoading(false) }]
      );
    }
  };

  // NOTE: This function is now replaced by MidtransWebViewScreen navigation
  // Open payment page in external browser (DEPRECATED)
  /*
  const openPaymentPage = async (paymentUrl, orderData) => {
    try {
      console.log('Opening payment page:', paymentUrl);

      const supported = await Linking.canOpenURL(paymentUrl);

      if (supported) {
        await Linking.openURL(paymentUrl);

        // Show status check dialog after opening payment
        setTimeout(() => {
          Alert.alert(
            'Status Pembayaran',
            'Setelah menyelesaikan pembayaran, aplikasi akan secara otomatis mendeteksi status pembayaran ketika Anda kembali.\n\nAnda juga dapat mengecek status secara manual.',
            [
              {
                text: 'Belum Bayar',
                style: 'cancel',
              },
              {
                text: 'Cek Status',
                onPress: () => {
                  if (currentOrderId.current) {
                    checkPaymentStatus(currentOrderId.current);
                  }
                },
              },
              {
                text: 'Sudah Bayar',
                onPress: () => {
                  if (currentOrderId.current) {
                    checkPaymentStatus(currentOrderId.current);
                  }
                },
              },
            ],
          );
        }, 1000);
      } else {
        Alert.alert(
          'Error',
          `Tidak dapat membuka halaman pembayaran.\n\nURL: ${paymentUrl}\n\nSilakan salin URL dan buka di browser manual.`,
          [
            { text: 'OK' },
            {
              text: 'Salin URL',
              onPress: () => {
                Alert.alert('URL Pembayaran', paymentUrl);
              },
            },
          ],
        );
      }
    } catch (error) {
      console.error('Error opening payment page:', error);
      Alert.alert(
        'Error',
        `Gagal membuka halaman pembayaran.\n\nError: ${error.message}\n\nURL: ${
          paymentUrl || 'N/A'
        }`,
      );
    }
  };
  */

  const BackIcon = () => (
    <Image
      source={require('./assets/back-icon.png')}
      style={{ width: 24, height: 24 }}
    />
  );

  return (
    <SafeAreaView style={{ flex: 1, backgroundColor: '#fff' }}>
      <ScrollView contentContainerStyle={{ paddingBottom: 30 }}>
        {/* Header */}
        <View style={styles.header}>
          <TouchableOpacity onPress={() => navigation?.goBack()}>
            <BackIcon />
          </TouchableOpacity>
          <Text style={styles.title}>Detail Checkout</Text>
        </View>

        {/* Info Pembeli */}
        <Text style={styles.sectionTitle}>Detail Pembeli</Text>
        <View style={styles.buyerInfo}>
          <Text style={styles.buyerName}>{buyer.name}</Text>
          <Text style={styles.buyerDetail}>{buyer.community}</Text>
          <Text style={styles.buyerDetail}>{buyer.phone}</Text>
        </View>

        {/* Detail Pesanan */}
        <Text style={styles.sectionTitle}>Detail Pesanan</Text>
        <View style={styles.orderInfo}>
          <Image source={order.image} style={styles.orderImage} />
          <View style={styles.orderDetails}>
            <Text style={styles.orderCategory}>{getCategoryDisplay(order.category)}</Text>
            <Text style={styles.orderName}>{order.name}</Text> 
            <Text style={styles.orderPrice}>{order.price}</Text>
          </View>
        </View>

        {/* Garis Pembatas Putus-putus */}
        <View style={styles.dividerContainer}>
          <View style={styles.dottedLine}>
            {Array.from({ length: 20 }).map((_, index) => (
              <View key={index} style={styles.dot} />
            ))}
          </View>
        </View>

        {/* Rincian Pembayaran */}
        <Text style={styles.sectionTitle}>Rincian Pembayaran</Text>
        <View style={styles.paymentInfo}>
          <View style={styles.paymentRow}>
            <Text style={styles.paymentLabel}>Metode Pembayaran</Text>
            <Text style={styles.paymentValue}>{payment.method}</Text>
          </View>
          <View style={styles.paymentRow}>
            <Text style={styles.paymentLabel}>Total Harga</Text>
            <Text style={styles.paymentValue}>{payment.total}</Text>
          </View>
        </View>

        {/* Tombol Bayar */}
        <TouchableOpacity
          style={[styles.payBtn, loading && styles.payBtnDisabled]}
          onPress={handlePayment}
          disabled={loading}
        >
          {loading ? (
            <ActivityIndicator color="#fff" />
          ) : (
            <Text style={styles.payBtnText}>Bayar</Text>
          )}
        </TouchableOpacity>
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 34,
    paddingHorizontal: 18,
  },
  title: {
    fontFamily: FontFamily.outfit_semibold,
    fontWeight: FontWeight.semibold,
    fontSize: 24,
    color: '#0070D8',
    marginLeft: 75,
  },
  sectionTitle: {
    fontFamily: FontFamily.semibold,
    fontWeight: FontWeight.semibold,
    fontSize: 18,
    color: '#000',
    marginHorizontal: 18,
    marginTop: 24,
    marginBottom: 12,
    letterSpacing: -0.96,
    lineHeight: 22,
  },
  buyerInfo: {
    backgroundColor: '#0070D8',
    marginHorizontal: 18,
    padding: 11,
    borderRadius: 12,
  },
  buyerName: {
    fontSize: 16,
    fontFamily: FontFamily.regular,
    fontWeight: FontWeight.regular,
    color: '#fff',
    marginBottom: 4,
    letterSpacing: -0.96,
    lineHeight: 22,
  },
  buyerDetail: {
    fontFamily: FontFamily.regular,
    fontWeight: FontWeight.regular,
    fontSize: 14,
    color: '#fff',
    marginBottom: 2,
    letterSpacing: -0.96,
    lineHeight: 22,
  },
  orderInfo: {
    flexDirection: 'row',
    paddingVertical: 10,
    marginHorizontal: 18,
    padding: 16,
    backgroundColor: '#0070D8',
    borderRadius: 12,
    alignItems: 'center',
  },
  orderImage: {
    width: 127,
    height: 129,
    borderRadius: 16,
    marginRight: 16,
  },
  orderDetails: {
    flex: 1,
    padding: 20
  },
  orderCategory: {
    fontFamily: FontFamily.medium,
    fontWeight: FontWeight.medium,
    fontSize: 16,
    color: '#fff',
    marginBottom: 4,
    letterSpacing: -0.5,
    lineHeight: 16,
  },
  orderName: {
    fontFamily: FontFamily.regular,
    fontWeight: FontWeight.regular,
    fontSize: 12,
    color: '#fff',
    marginBottom: 50,
    letterSpacing: -0.96,
    lineHeight: 22,
  },
  orderPrice: {
    fontFamily: FontFamily.regular,
    fontWeight: FontWeight.regular,
    fontSize: 16,
    color: '#fff',
  },
  paymentInfo: {
    padding: 16,
    borderRadius: 8,
  },
  paymentRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  paymentLabel: {
    fontFamily: FontFamily.regular,
    fontWeight: FontWeight.regular,
    fontSize: 16,
    color: '#000',
    flex: 1,
    letterSpacing: -0.96,
    lineHeight: 22,
  },
  paymentValue: {
    fontFamily: FontFamily.regular,
    fontWeight: FontWeight.regular,
    fontSize: 16,
    color: '#000',
    textAlign: 'right',
    flex: 1,
    letterSpacing: -0.96,
    lineHeight: 22,
  },
  payBtn: {
    backgroundColor: '#0070D8',
    borderRadius: 32,
    alignItems: 'center',
    paddingVertical: 15,
    marginTop: 24,
    marginHorizontal: 120,
  },
  payBtnDisabled: {
    backgroundColor: '#ccc',
  },
  payBtnText: {
    fontFamily: FontFamily.medium,
    fontWeight: FontWeight.medium,
    color: '#fff',
    fontSize: 16,
    letterSpacing: -0.96,
    lineHeight: 22,
  },
  
  // Styling untuk garis putus-putus
  dividerContainer: {
    marginHorizontal: 20,
    marginTop: 20,
    alignItems: 'center',
  },
  dottedLine: {
    flexDirection: 'row',
    width: '100%',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 5,
  },
  dot: {
    width: 15,
    height: 2,
    borderRadius: 4, // Membuat bentuk bulat (round)
    backgroundColor: '#0070D8',
    borderWidth: 1,
    borderColor: '#0070D8',
    borderStyle: 'solid',
  },
});
